<h2>A Propos</h2>
<hr>
<div class="row">
    <hr class="col-sm-4">
    <h2 class="col-sm-2 text-center">Historique</h2>
    <hr class="col-sm-4">
</div>
<div class="row historique">
    <div class="col-sm-3 text-center">
        <img src="<?= $this->basePath('img/thiant1.png') ?>" class="img-responsive" width="200px" height="auto"  alt="New York" >            </div>
        <div class="col-sm-9" >
            <p class="text-justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id rhoncus velit. Proin nisi neque, finibus 
                sit amet ante a, commodo malesuada turpis. Fusce nec sollicitudin velit. Fusce vel augue nunc. Phasellus 
                feugiat nisi enim, ac tincidunt risus porttitor ut. Nunc mollis sit amet tortor a dignissim. Nullam egestas
                imperdiet urna cursus vulputate. Praesent ullamcorper lacus nibh, sed tristique erat convallis eleifend
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda fuga repellendus id at perferendis ut temporibus reprehenderit. Reprehenderit, cumque doloremque? Sequi ab voluptate expedita, dolore enim placeat dolorem pariatur impedit.
            </p>
        </div>
    </div>
    <div class="row">
        <hr class="col-sm-4">
        <h2 class="col-sm-2 text-center">Objectif</h2>
        <hr class="col-sm-4">
    </div>
    <div class="row objectif">
        <div class="col-sm-9 text-center">
            <p class="text-justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id rhoncus velit. Proin nisi neque, finibus 
                sit amet ante a, commodo malesuada turpis. Fusce nec sollicitudin velit. Fusce vel augue nunc. Phasellus 
                feugiat nisi enim, ac tincidunt risus porttitor ut. Nunc mollis sit amet tortor a dignissim. Nullam egestas
                imperdiet urna cursus vulputate. Praesent ullamcorper lacus nibh, sed tristique erat convallis eleifend
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis iusto eius optio fugit consectetur, aliquid minima pariatur doloribus veritatis incidunt laborum dolorum hic repellendus deserunt sed quibusdam ad ea quasi.
            </p>
        </div>
        <div class="col-sm-3 text-center" >
            <img src="<?= $this->basePath('img/thiant1.png') ?>" class="img-responsive" width="200px"  alt="New York" >
        </div>
    </div>
    <div class="localisation" style="height:200px">
        <a target="_blank" href="https://www.google.com/maps/place/EMPRO+SN/@14.7111393,-17.4506503,17z/data=!3m1!4b1!4m5!3m4!1s0xec173eabb264a3f:0x3b03193b00bf067c!8m2!3d14.7111341!4d-17.4484616?hl=fr" class="btn samabtn btn-lg">Localiser sur GoogleMap</a>
</div>