<div class="contact">
<h1>Contactez-Nous</h1>
<hr>
<div class="row">
    <div class="col-sm-4 info">
        <h4 class="text-center">Informations</h4>
        <div class="text">
            <img src="<?= $this->basePath('img/icon1.png') ?>" width="30px" alt="" srcset="">
            <a href="tel:+221778482414"> 77 848 24 14 / 77 159 85 41</a>
        </div>
        <div class="text">
            <img src="<?= $this->basePath('img/icon2.png') ?>" width="30px" alt="icone"/>
            <a href="mailto:elementboromkhass@gmail.com"> ebkdesign1@gmail.com</a>
        </div>
        <div class="text">
            <img src="<?= $this->basePath('img/icon3.png') ?>" width="30px" alt="" srcset="">
            <a href="loc:Commune Biscuiterie"> Commune de Biscuiterie</a>
        </div>  
    </div>
    <div class="con col-sm-5 ml-auto">
        <form>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Prenom</label>
                    <input type="text" class="form-control" id="inputEmail4" placeholder="">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputPassword4">Nom</label>
                    <input type="text" class="form-control" id="inputPassword4" placeholder="">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="inputEmail4" placeholder="">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputPassword4">Telephone</label>
                    <input type="number" class="form-control" id="inputPassword4" placeholder="">
                </div>
            </div>
            <div class="form-group">
                <label for="inputAddress">Adresse</label>
                <input type="text" class="form-control" id="inputAddress" placeholder="">
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Message</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div> 
            <button type="submit" class="btn nav-active">Envoyer</button>
        </form>
    </div>
</div>
</div>