<div class="sunujumb">
    <h1>Bienvenue sur <span class="zf-green">EBK Design</span></h1>

    <p>
        EBK_Design est une structure créée  en 2017 par des jeunes étudiants. Elle évolue dans le domaine de l'informatique plus précisement dans le domaine de l'infographie. Quand on parle del'infographie on fait allusion au multumédia  c'est - à - dire tous ce qui est conception de logo, affiche, flyers montage video...
    </p>

    <p><a class="btn samabtn btn-lg" href="<?= $this->url('apropos') ?>">Voir plus&raquo;</a></p>
    <?= ($this->page) ?>
</div>
<h2 class="service"><span > Nos Services</span></h2>
<div class="row main text-center service-row">
    <div class="col-md-3 pb-3 col-sm-4 col-6">
        <div class="service-container">
            <div class="header">
                <img src="<?= $this->basePath('img/icone1.png') ?>" class="img-responsive" width="80px" height="80px" alt="" srcset="">
            </div>
        </div>
        <div>       
            <button class="btn nav-active"><a class="btn samabtn" href="<?= $this->url('service') ?>">Logo</a></button>        
        </div> 
    </div>
    <div class="col-md-3 pb-3 col-sm-4 col-6">
        <div class="service-container">
            <div class="header">
                <img src="<?= $this->basePath('img/icone4.png') ?>" class="img-responsive" width="80px" height="80px" alt="" srcset="">
            </div>
        </div>
        <button class="btn nav-active"><a class="btn samabtn" href="<?= $this->url('service') ?>">Affiche</a></button> 
    </div>
    <div class="col-md-3 pb-3 col-sm-4 col-6">
        <div class="service-container">
            <div class="header">
                <img src="<?= $this->basePath('img/icone3.png') ?>" class="img-responsive" width="80px" height="80px" alt="" srcset="">
            </div>
        </div>
        <button class="btn nav-active"><a class="btn samabtn" href="<?= $this->url('service') ?>">flyers</a></button> 
    </div>
    <div class="col-md-3 pb-3 col-sm-4 col-6">
        <div class="service-container">
            <div class="header">
                <img src="<?= $this->basePath('img/icone2.png') ?>" class="img-responsive" width="80px" height="80px" alt="" srcset="">
            </div>
        </div>
        <button class="btn nav-active"><a class="btn samabtn" href="<?= $this->url('service') ?>">Vidéo</a></button> 
    </div>
</div>
<h2 class="service"><span>Réalisations</span></h2>
<div class="sunucarousel">
    
    <div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
    <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
        <li data-target="#demo" data-slide-to="3"></li>
        <li data-target="#demo" data-slide-to="4"></li>
    </ul>
  
  <!-- The slideshow -->
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="<?= $this->basePath('img/khalil.png') ?>" class="img-responsive" alt="Los Angeles" >
        </div>
        <div class="carousel-item">
            <img src="<?= $this->basePath('img/visage.png') ?>"class="img-responsive"  alt="Chicago" >
        </div>
        <div class="carousel-item">
            <img src="<?= $this->basePath('img/revision.png') ?>" class="img-responsive"  alt="New York" >
        </div>
        <div class="carousel-item">
            <img src="<?= $this->basePath('img/thiant.png') ?>" class="img-responsive"  alt="New York" >
        </div>
        <div class="carousel-item">
            <img src="<?= $this->basePath('img/logok.png') ?>" class="img-responsive"  alt="New York" >
        </div>
    </div>
    
    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
    </div>
</div>
