<h1>Services</h1>
<hr>
<div class="row">
    <div class="col-sm-3 info">
        <h4 class="text-center">Sidebar</h4>
        <div class="text">
            <img src="<?= $this->basePath('img/icon1.png') ?>" width="30px" alt="" srcset="">
            <a href="tel:+221778482414"> 77 848 24 14 / 77 159 85 41</a>
        </div>
        <div class="text">
            <img src="<?= $this->basePath('img/icon2.png') ?>" width="30px" alt="icone"/>
            <a href="mailto:elementboromkhass@gmail.com"> elementboromkhass@gmail.com</a>
        </div>
        <div class="text">
            <img src="<?= $this->basePath('img/icon3.png') ?>" width="30px" alt="" srcset="">
            <a href="loc:Commune Biscuiterie"> Commune de Biscuiterie</a>
        </div>  
    </div>
    <div class="row col-sm-9">    
    <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Conception logo</h4>
                </div>
                <div class="card-body">
                    <img src="<?= $this->basePath('img/icone1.png') ?>" width="100%" alt="" srcset="">
                    <div>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati modi pariatur ex voluptas maiores.
                    </div>
                    <p><a class="btn nav-active pull-right" href="" >Detail &raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Conception logo</h4>
                </div>
                <div class="card-body">
                    <img src="<?= $this->basePath('img/icone1.png') ?>" width="100%" alt="" srcset="">
                    <div>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati modi pariatur ex voluptas maiores.
                    </div>
                    <p><a class="btn nav-active pull-right" href="" >Detail &raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Conception logo</h4>
                </div>
                <div class="card-body">
                    <img src="<?= $this->basePath('img/icone1.png') ?>" width="100%" alt="" srcset="">
                    <div>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati modi pariatur ex voluptas maiores.
                    </div>
                    <p><a class="btn nav-active pull-right" href="" >Detail&raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Conception logo</h4>
                </div>
                <div class="card-body">
                    <img src="<?= $this->basePath('img/icone1.png') ?>" width="100%" alt="" srcset="">
                    <div>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati modi pariatur ex voluptas maiores.
                    </div>
                    <p><a class="btn nav-active pull-right" href="" >Detail &raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Conception logo</h4>
                </div>
                <div class="card-body">
                    <img src="<?= $this->basePath('img/icone1.png') ?>" width="100%" alt="" srcset="">
                    <div>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati modi pariatur ex voluptas maiores.
                    </div>
                    <p><a class="btn nav-active pull-right" href="" >Detail&raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Conception logo</h4>
                </div>
                <div class="card-body">
                    <img src="<?= $this->basePath('img/icone1.png') ?>" width="100%" alt="" srcset="">
                    <div>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati modi pariatur ex voluptas maiores.
                    </div>
                    <p><a class="btn nav-active pull-right" href="" >Detail &raquo;</a></p>
                </div>
            </div>
        </div>
    </div>
        
</div>
</div>