<h1>Services</h1>
<hr>
<div class="row">
    <div class="col-sm-3 info sidebar">
        <h4 class="text-center">Autres services</h4>
        <div class="text">
            <div class="row">
                <div class="col-3">
                    <img src="<?= $this->basePath('img/icone1.png') ?>" width="50px" height="50px" alt="" srcset="">
                </div>
                <div class="col-9">
                    <h6 class="">Logo</h6>
                    <p class="text-muted small">Creativité au centre de notre univers</p>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <img src="<?= $this->basePath('img/icone2.png') ?>" width="50px" height="50px" alt="" srcset="">
                </div>
                <div class="col-9">
                    <h6 class="">Video</h6>
                    <p class="text-muted small">Creativité au centre de notre univers</p>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <img src="<?= $this->basePath('img/icone3.png') ?>" width="50px" height="50px" alt="" srcset="">
                </div>
                <div class="col-9">
                    <h6 class="">Flyers</h6>
                    <p class="text-muted small">Creativité au centre de notre univers</p>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <img src="<?= $this->basePath('img/icone4.png') ?>" width="50px" height="50px" alt="" srcset="">
                </div>
                <div class="col-9">
                    <h6 class="">Affiche</h6>
                    <p class="text-muted small">Creativité au centre de notre univers</p>
                </div>
            </div>
        </div>
        <hr>
        <h4 class="text-center">Contactez-nous</h4>
        <div class="text">
            <div class="row text-left">
                    <div class="col-2">
                        <img src="<?= $this->basePath('img/icon1.png') ?>" width="30px" height="30px" alt="" srcset="">
                    </div>
                    <div class="col-10">
                        <a href="tel:+778482414">+221 77 848 24 14</a>
                    </div>
                </div>
            <div class="row">
                    <div class="col-2">
                        <img src="<?= $this->basePath('img/icon2.png') ?>" width="30px" height="30px" alt="" srcset="">
                    </div>
                    <div class="col-10">
                        <a href="mailto:ebkdesign1@gmail.com">ebkdesign1@gmail.com</a>
                    </div>
                </div>
        </div>
    </div>
    <div class="row col-sm-9">
        <div class="card-columns">
            <div class="card">
                <div class="card-header">
                    <img class="card-img-top-costum" src="<?= $this->basePath('img/icone1.png') ?>" width="80px" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h5 class="card-title">Conception logo</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn samabtn">Commander</a>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <img class="card-img-top-costum" src="<?= $this->basePath('img/icone2.png') ?>" width="80px" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h5 class="card-title">Montage Video</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn samabtn">Commander</a>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <img class="card-img-top-costum" src="<?= $this->basePath('img/icone3.png') ?>" width="80px" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h5 class="card-title">Flyers</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn samabtn">Commander</a>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <img class="card-img-top-costum" src="<?= $this->basePath('img/icone4.png') ?>" width="80px" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h5 class="card-title">Affiche</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn samabtn">Commander</a>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <img class="card-img-top-costum" src="<?= $this->basePath('img/icone1.png') ?>" width="80px" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h5 class="card-title">Shooting</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn samabtn">Commander</a>
                </div>
            </div>
        </div>
    </div>
</div>